In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('12-siT8STLi7v4y-MA7709Od1XcrowAEc')

# PyTorch

### An short introduction about PyTorch and about the chosen functions.

# What is PyTorch?

PyTorch is a Python-based scientific computing package that uses the power of graphics processing units(GPU). 
It is also one of the preferred deep learning research platforms built to provide maximum flexibility and speed. 
It is known for providing two of the most high-level features:
    tensor computations with strong GPU acceleration support 
    building deep neural networks on a tape-based autograd systems.

There are many existing Python libraries which have the potential to change how deep learning and artificial intelligence are performed, and this is one such library. One of the key reasons behind PyTorch’s success is it is completely Pythonic and one can build neural network models effortlessly. It is still a young player when compared to its other competitors, however, it is gaining momentum fast.

### Install

<mark style="background-color: Blue">__In CPU__</mark>

__For Windows__

* Install PyTorch using conda
      conda install pytorch torchvision cpuonly -c pytorch

In [ ]:
# Import the torch library
import torch

## PyTorch Functions

### Function 1 - torch.linspace

torch.linspace is used to create a 1D equally spaced tensor between the start and end values.
We can specify the size of the tensor with the *steps parameters. The default value is 100.

In [ ]:
#with out step parameter 
torch.linspace(1, 5)

tensor([1.0000, 1.0404, 1.0808, 1.1212, 1.1616, 1.2020, 1.2424, 1.2828, 1.3232,
        1.3636, 1.4040, 1.4444, 1.4848, 1.5253, 1.5657, 1.6061, 1.6465, 1.6869,
        1.7273, 1.7677, 1.8081, 1.8485, 1.8889, 1.9293, 1.9697, 2.0101, 2.0505,
        2.0909, 2.1313, 2.1717, 2.2121, 2.2525, 2.2929, 2.3333, 2.3737, 2.4141,
        2.4545, 2.4949, 2.5354, 2.5758, 2.6162, 2.6566, 2.6970, 2.7374, 2.7778,
        2.8182, 2.8586, 2.8990, 2.9394, 2.9798, 3.0202, 3.0606, 3.1010, 3.1414,
        3.1818, 3.2222, 3.2626, 3.3030, 3.3434, 3.3838, 3.4242, 3.4646, 3.5051,
        3.5455, 3.5859, 3.6263, 3.6667, 3.7071, 3.7475, 3.7879, 3.8283, 3.8687,
        3.9091, 3.9495, 3.9899, 4.0303, 4.0707, 4.1111, 4.1515, 4.1919, 4.2323,
        4.2727, 4.3131, 4.3535, 4.3939, 4.4343, 4.4747, 4.5152, 4.5556, 4.5960,
        4.6364, 4.6768, 4.7172, 4.7576, 4.7980, 4.8384, 4.8788, 4.9192, 4.9596,
        5.0000])

In [ ]:
# with step parameter
torch.linspace(start = 1 , end = 5 , steps = 2)

tensor([1., 5.])

### Function 2 - torch.eye

torch.eye returns a 2D tensor with the values of diagonals as 1 and other values as 0.
The function expects two parameters — n and m .(If m is not specified, then it returns a 2D tensor of size n*n)

In [ ]:
torch.eye(n=3, m=4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [ ]:
#if m not specified then it will give n*n tensor
torch.eye(n=3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Function 3 - torch.full

torch.full returns a tensor of size mentioned in the function with the values filled with fill_value 
The size can be a list or a tuple.

In [ ]:
# size is tuple
torch.full(size=(3,2), fill_value=10)

tensor([[10., 10.],
        [10., 10.],
        [10., 10.]])

In [ ]:
#size is list
torch.full(size=[2, 3, 4], fill_value=5)

tensor([[[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]],

        [[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]]])

### Function 4 - torch.one

torch.one returns a Tensor of size *size filled with 1. By default, the returned Tensor has the same torch.dtype and torch.device as this tensor.

In [ ]:
#Construct a matrix filled ones and of dtype long:
a = torch.ones(4,3, dtype=torch.long)
a

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

### Function 5 - torch.new_ones

torch.new_ones works with existing tensor. x will inherit the datatype from a and it will run on same device as defined in a.(By default it will run on CPU)

In [ ]:
# new methods take in sizes. Also data type changed from long to double
x = a.new_ones(6,5, dtype=torch.double)
b

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

### Function 6 - torch.zeros

torch.one returns a Tensor of size *size filled with 0. By default, the returned Tensor has the same torch.dtype and torch.device as this tensor.

In [ ]:
#Construct a matrix filled zeros and of dtype long:
b = torch.zeros(4,3, dtype=torch.long)
b

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

### Function 7 - torch.cat

torch.cat concatenates a sequence of tensors over the specified dimension dim. 
**Note: All the tensors must be of the same shape

In [ ]:
a = torch.ones(3,2)
b = torch.zeros(3,2)
torch.cat((a, b)) # default dim=0

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
# if we want to filled with other number we can use the full function and then cat both the tensors
x = torch.full((3,3), fill_value=4)
y = torch.full((3,3), fill_value=7)
torch.cat((x, y), dim=1)

tensor([[4., 4., 4., 7., 7., 7.],
        [4., 4., 4., 7., 7., 7.],
        [4., 4., 4., 7., 7., 7.]])

### Function 8: torch.take

torch.take returns a tensor with the elements of the input tensors at the given indices. The input tensor is treated as a 1D tensor to return the values.

In [ ]:
# 1D input Tensor
t1 = torch.tensor([10, 20, 30, 40, 50])
torch.take(t1, torch.tensor([2]))

tensor([30])

In [ ]:
# 2D input tensor
t2 = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.take(t2, torch.tensor([3,4]))

tensor([4, 5])

### Function 9: torch.unbind

torch.unbind removes a tensor dimension along the given dimension *dim.
The default dimension is 0 i.e. dim=0

In [ ]:
ub1 = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.unbind(ub1)

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [ ]:
ub2 = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.unbind(ub2, dim=1)

(tensor([1, 4]), tensor([2, 5]), tensor([3, 6]))

### Function 7: torch.Tensor.clone

torch.Tensor.clone returns a copy of the tensor with the same size and data type.
**Note: When we create a copy of the tensor using x=y , changing one variable also affects the other variable since it points to the same memory location.

In [ ]:
tc1 = torch.tensor([[1., 2.],
                  [3., 4.],
                  [5., 6.]])
# Assign the tc1 tensor to tc2
tc2 = tc1
#Lets change the value in the matrix and we can see the same value update in tc2 as well
tc1[1,0]=9
tc1,tc2

(tensor([[1., 2.],
         [9., 4.],
         [5., 6.]]),
 tensor([[1., 2.],
         [9., 4.],
         [5., 6.]]))

In [ ]:
#To avoid this, we can create a deepcopy of the tensor using .clone method.
tc1 = torch.tensor([[1., 2.],
                  [3., 4.],
                  [5., 6.]])
tc2 = tc1.clone()
tc1[1,0]=9
tc1,tc2

(tensor([[1., 2.],
         [9., 4.],
         [5., 6.]]),
 tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]))

### Commit and upload the notebook
As a final step, we can save and commit out work using the jovian library.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

<IPython.core.display.Javascript object>

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
